### ISSUE TITLE
Window-Manager – Search filter is not removed when we delete keyword text from the search input box

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#276]
Summary:
Window-Manager – Search filter is not removed when we delete keyword text from the search input box

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Click search and Enter keyword as “Demo” and Hit search button
4.Now using keyboard select a keyword and click Delete button

## Expected Result ###
Window-Manager – Search filter should be removed when we delete keyword text from the search input box
### Actual  Result ###
Window-Manager – Search filter is not removed when we delete keyword text from the search input box

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by youdare** [comment]
https://youtu.be/zl3l199rIpI

**Comment by youdare** [comment]
@sdgun Able to reproduce with mentioned steps.

Go to https://connect.topcoder-dev.com/
Log in with pshah_manager/topcoder123
3.Click search and Enter keyword as “Demo” and Hit search button
4.Now using keyboard select a keyword and click Delete button

Please check the video, If we delete the keyword from the search using  our physical keyboard, we can reproduce this issue 

After deleting just click outside of page.

**Comment by sdgun** [comment]
I am sorry this is an incomplete Report: **After deleting just click outside of page.** is missing in the steps. You have to provide complete steps and all the test data in the submission phase. I can't accept any re-appeals and new steps and test data now because we are in the review phase

Please check the **ISSUE REPORTING GUIDELINES** > IMPORTANT NOTE:

__Missing or Incorrect details to ANY of the above fields will mark the bug report as INCOMPLETE._ 

_For example Incorrect/Missing Reported URL (This is the URL where you can see the bug, You can copy paste the URL from the browser address bar), Screenshot/Screencast (If it is a UI issue, You have to mark it on the screenshot), Incorrect Actual and Expected results etc.__

**Comment by youdare** [comment]
Thanks @sdgun
