### ISSUE TITLE
Window-Manager – Text file is converted and uploaded as HTML File while dragging and dropping the uploaded text file.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/connect-test-cycle-1#328]
Summary:
Window-Manager – Text file is converted and uploaded as HTML File while dragging and dropping the uploaded text file.
Note:- Here in HTML file as random file name.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create a new App project
4.Go to Specification and Go to file section
5. Upload a Text File
6.Now Drag and Drop the Uploaded text file to upload
## Expected Result ###
Window-Manager –App should not allow to drag and drop the uploaded text file.

### Actual  Result ###
Window-Manager – Text file is converted and uploaded as HTML File while dragging and dropping the uploaded text file.

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and details
Expected Result: App should not allow to drag and drop the uploaded text file. > System must allow uploading text files.

No Image/video attached - Incomplete

**Comment by youdare** [comment]
@sdgun attcahing now i dont know how i missed, Please consider this.

![image](https://user-images.githubusercontent.com/31862600/36521356-69e36d32-17bc-11e8-8755-40eeab37120f.png)
![image](https://user-images.githubusercontent.com/31862600/36521365-7cd2af52-17bc-11e8-8f66-e62ae974a036.png)

**Comment by sdgun** [comment]
Can't reproduce the bug using the provided steps and details. Dragging and dropping a text file to the placeholder will recognize it as a text file always.

**TIPS:** 
1. For Functional bugs provide video
2. Specify the test data you have entered on the bug report always, so that reviewer can use that to produce your bug
3. This particular bug is related to an attachment, so better to attach the test document as well
4. Correctly provide the environment details. I can see 'Browser: Chrome' as the environment in your bug report but then you have provided FF screenshots. 
5. Always provide the browser version. Any of your bug reports won't have a version of it.
6. Finally: carefully read the **ISSUE REPORTING GUIDELINES**. This may vary from challenge to challenge

This may reduce bug report rejection.

**You have to provide all these details before the submission phase ends.**
